name: CI tests
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  tests:
    name: Run tests for python ${{matrix.python}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]        

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Prepare python 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      
      - name: Install requirements
        run: pip install -r requirements.txt 
        
      - name: Run tests
        run: python -m unittest discover -s tests -v